### ISSUE TITLE
Support Windows Containers

### ISSUE THREAD

**Issue by david-jarman** [Microsoft/ApplicationInsights-Kubernetes#105]
Using this package in a Windows container will cause the application to throw an exception on startup:

```
System.IO.FileNotFoundException: File contains container id does not exist.
File name: '/proc/self/cgroup'
   at Microsoft.ApplicationInsights.Kubernetes.KubeHttpClientSettingsProvider.FetchContainerId(String pathToCGroup)
   at Microsoft.ApplicationInsights.Kubernetes.KubeHttpClientSettingsProvider..ctor(ILogger`1 logger, String pathToToken, String pathToCert, String pathToNamespace, String pathToCGroup, String kubernetesServiceHost, String kubernetesServicePort)
   at Microsoft.ApplicationInsights.Kubernetes.KubernetesModule.<>c.<BuildK8sServiceCollection>b__3_0(IServiceProvider p)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass22_0.<RealizeService>b__0(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.ApplicationInsights.Kubernetes.KubernetesModule.EnableKubernetes(IServiceCollection serviceCollection, TelemetryConfiguration configuration, Nullable`1 timeout)
```

Since there is no cgroups concept in Windows, the container id must be retrieved a different way. A potential solution for docker containers is to use the "computername" environment variable. It is set to a shortened version of the container id.

**Comment by xiaomi7732** [comment]
@david-jarman,
Thank you for the feedback. Getting computer name is part of the formula and there's more after that. If you are interested in code, here the initialization settings is provided:
https://github.com/Microsoft/ApplicationInsights-Kubernetes/blob/develop/src/ApplicationInsights.Kubernetes/K8sHttpClient/KubeHttpClientSettingsProvider.cs

Give me a few days to look into how big the scope is to support windows containers and I'll get back to you later.

**Comment by xiaomi7732** [comment]
@david-jarman I investigated a bit around windows containers on Kubernetes. 
I have an issue querying host.
For example, by sending request to: https://10.0.0.1/v1/api/namespace/default/pods within the container, I always got timeout.
Lately, I managed get curl running in the container, can't reach 10.0.0.1 either:
```
C:\src\curl>curl -kv https://10.0.0.1/api/v1/namespace/default/pods
*   Trying 10.0.0.1...
* TCP_NODELAY set
* connect to 10.0.0.1 port 443 failed: Timed out
* Failed to connect to 10.0.0.1 port 443: Timed out
* Closing connection 0
curl: (7) Failed to connect to 10.0.0.1 port 443: Timed out
```
After all, querying host is the way used to get Kubernetes properties. If there's no quick solution, I'll conclude this as feature for the future.

Sample implementation could be found here:
https://github.com/xiaomi7732/ApplicationInsights-Kubernetes/tree/dev/saars/win-container-1

**Comment by david-jarman** [comment]
I exec'd into one of the windows container pods in my k8s cluster and I was able to retrieve the pod list using the exact url you used (however, I used Invoke-WebRequest in powershell, and I added the authorization header to the request).

**Comment by david-jarman** [comment]
Thanks! I built the image in your private branch but I got an cast object exception when I ran the image in my cluster:

```
info: Microsoft.ApplicationInsights.Kubernetes.KubernetesModule[0]
      ApplicationInsights.Kubernetes.Version:1.0.0-private-201804141814
dbug: Microsoft.ApplicationInsights.Kubernetes.KubeHttpSettingsWinContainerProvider[0]
      Kubernetes base address: https://10.0.0.1:443/
dbug: Microsoft.ApplicationInsights.Kubernetes.KubeHttpSettingsWinContainerProvider[0]
      Found certificate file path: C:\var\run\secrets\kubernetes.io\serviceaccount\..4984_18_04_17_35_24.871999060\ca.crt
dbug: Microsoft.ApplicationInsights.Kubernetes.KubeHttpSettingsWinContainerProvider[0]
      Found namespace file path: C:\var\run\secrets\kubernetes.io\serviceaccount\..4984_18_04_17_35_24.871999060\namespace
dbug: Microsoft.ApplicationInsights.Kubernetes.KubeHttpSettingsWinContainerProvider[0]
      Found token file paht: C:\var\run\secrets\kubernetes.io\serviceaccount\..4984_18_04_17_35_24.871999060\token
dbug: Microsoft.ApplicationInsights.Kubernetes.KubeHttpSettingsWinContainerProvider[0]
      Token file path: C:\var\run\secrets\kubernetes.io\serviceaccount\..4984_18_04_17_35_24.871999060\token
dbug: Microsoft.ApplicationInsights.Kubernetes.KubeHttpClient[0]
      Access token is not null. Set default request header.
dbug: Microsoft.ApplicationInsights.Kubernetes.K8sQueryClient[0]
      Full url: https://10.0.0.1/api/v1/namespaces/default/pods.
      Request Message: Method: GET, RequestUri: 'https://10.0.0.1/api/v1/namespaces/default/pods', Version: 1.1, Content: <null>, Headers:
      {
      }
dbug: Microsoft.ApplicationInsights.Kubernetes.K8sQueryClient[0]
      Default Header: Authorization: Bearer <redacted>
      
warn: Microsoft.ApplicationInsights.Kubernetes.K8sEnvironmentFactory[0]
      Query exception while trying to get pod info: Unable to cast object of type 'System.Security.Cryptography.X509Certificates.X509Certificate' to type 'System.Security.Cryptography.X509Certificates.X509Certificate2'.
dbug: Microsoft.ApplicationInsights.Kubernetes.K8sEnvironmentFactory[0]
         at Internal.Cryptography.Pal.StorePal.LinkFromCertificateCollection(X509Certificate2Collection certificates)
         at Internal.Cryptography.Pal.FindPal..ctor(X509Certificate2Collection findFrom, X509Certificate2Collection copyTo, Boolean validOnly)
         at Internal.Cryptography.Pal.FindPal.FindFromCollection(X509Certificate2Collection coll, X509FindType findType, Object findValue, Boolean validOnly)
         at System.Security.Cryptography.X509Certificates.X509Certificate2Collection.Find(X509FindType findType, Object findValue, Boolean validOnly)
         at System.Net.Http.WinHttpCertificateHelper.GetEligibleClientCertificate(X509Certificate2Collection candidateCerts)
         at System.Net.Http.WinHttpHandler.SetRequestHandleClientCertificateOptions(SafeWinHttpHandle requestHandle, Uri requestUri)
         at System.Net.Http.WinHttpHandler.SetRequestHandleOptions(WinHttpRequestState state)
         at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
         at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
         at Microsoft.ApplicationInsights.Kubernetes.K8sQueryClient.<GetAllItemsAsync>d__12`1.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
         at Microsoft.ApplicationInsights.Kubernetes.K8sQueryClient.<GetMyPodAsync>d__7.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
         at Microsoft.ApplicationInsights.Kubernetes.K8sEnvironmentFactory.<SpinWaitUntilGetPod>d__6.MoveNext()
```

**Comment by xiaomi7732** [comment]
@david-jarman I have an theory that might fix the issue. Code updated and new test package is uploaded. Could you please give that another shoot: 
https://github.com/xiaomi7732/ApplicationInsights-Kubernetes/tree/dev/saars/win-container-1/examples/WindowsContainer
Please making sure the new package is referenced:
```xml
    <PackageReference Include="Microsoft.ApplicationInsights.Kubernetes" Version="1.0.0-private-201804182024" />
```

**Comment by david-jarman** [comment]
Looks good from my end. Let me know if you need anything else. Thanks!
