### ISSUE TITLE
Exception while initializing Microsoft.ApplicationInsights.Kubernetes.KubernetesTelemetryInitializer

### ISSUE THREAD

**Issue by frankbuckley** [Microsoft/ApplicationInsights-Kubernetes#106]
We are seeing this error repeatedly reported in our telemetry with 1.0.0-beta6:

	AI (Internal): [msg=Log Error];[msg=Exception while initializing Microsoft.ApplicationInsights.Kubernetes.KubernetesTelemetryInitializer, exception message - Newtonsoft.Json.JsonSerializationException: Error getting value from 'HttpMethod' on 'Microsoft.ApplicationInsights.DataContracts.RequestTelemetry'. ---> System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
	   at System.Collections.Concurrent.ConcurrentDictionary`2.ThrowKeyNotFoundException()
	   at System.Collections.Concurrent.ConcurrentDictionary`2.get_Item(TKey key)
	   at Newtonsoft.Json.Serialization.ExpressionValueProvider.GetValue(Object target)
	   --- End of inner exception stack trace ---
	   at Newtonsoft.Json.Serialization.ExpressionValueProvider.GetValue(Object target)
	   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CalculatePropertyValues(JsonWriter writer, Object value, JsonContainerContract contract, JsonProperty member, JsonProperty property, JsonContract& memberContract, Object& memberValue)
	   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
	   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
	   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
	   at Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer)
	   at Microsoft.ApplicationInsights.Kubernetes.KubernetesTelemetryInitializer.Initialize(ITelemetry telemetry)
	   at Microsoft.ApplicationInsights.TelemetryClient.Initialize(ITelemetry telemetry)]

Seen in multiple containers running multiple apps across 2 clusters running Kubernetes 1.9.6 and Kubernetes nginx-ingress-controller 0.12.0.

Linux containers based on microsoft/aspnetcore:2.0.6. ASP.NET Core apps are configured to use forwarded headers.

**Comment by xiaomi7732** [comment]
@frankbuckley If I understand right, you are seeing the issue but the application insights data is correctly sent and you can see the data in your application insights, right?
Could you please confirm if your log level has been set to 'Trace'?
I believe this is the line of the code causing the trouble:
```
    _logger.LogTrace(JsonConvert.SerializeObject(telemetry));
```
Trying to serialize telemetry object with Json.NET is known to cause trouble & I think that is a mistake for that line of code.

@karolz-ms Thanks for the suggestion. Serialization is not needed other than logging, which will only be invoked for Tracing level of the issues. At this stage, I don't see the performance gain for switching to a raw implementation for data serialization.

**Comment by frankbuckley** [comment]
@xiaomi7732 Yes - application insights data is sent from our apps (including additional Kubernetes data), together with the "AI (Internal)" trace. However, no - LogLevel = Warning.

**Comment by xiaomi7732** [comment]
@frankbuckley Thanks for pointing it out. I didn't realize the exception happens earlier than the logging happens.
Simple reproduce:
```
RequestTelemetry requestTelemetry = new RequestTelemetry();
string jsonString = JsonConvert.SerializeObject(requestTelemetry, Formatting.Indented);
```
I'll submit a PR for the fix.

**Comment by frankbuckley** [comment]
Thanks for the quick fix @xiaomi7732. Are you going to push a fresh build to NuGet?

**Comment by xiaomi7732** [comment]
@frankbuckley Yes I will. Per my current priorities, I am thinking about doing that the next week.
