### ISSUE TITLE
Exception thrown upon detecting container id failure

### ISSUE THREAD

**Issue by xiaomi7732** [microsoft/ApplicationInsights-Kubernetes#297]
This is reported by @blushingpenguin in #290.

TL;DR - when auto-detection for the container id failed, an exception is thrown, breaking the working flow. The expectation is for a string.Empty to be returned as the container id.

- [x] Fix in 2.x
- [x] Verify if the same fix is needed in 3.x.

Copy of the callstack provided:

```csharp
Unhandled exception. System.InvalidOperationException: Failed fetching container id.
   at Microsoft.ApplicationInsights.Kubernetes.KubeHttpClientSettingsBase.GetContainerIdOrThrow()
   at Microsoft.ApplicationInsights.Kubernetes.KubeHttpClientSettingsBase..ctor(String kubernetesServiceHost, String kubernetesServicePort, 
IEnumerable`1 containerIdProviders)
   at Microsoft.ApplicationInsights.Kubernetes.KubeHttpClientSettingsProvider..ctor(IEnumerable`1 containerIdProviders, String pathToToken, 
String pathToCert, String pathToNamespace, String kubernetesServiceHost, String kubernetesServicePort)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

**Comment by xiaomi7732** [comment]
@blushingpenguin PR ready for review. Check out #298 for details.

**Comment by xiaomi7732** [comment]
Fix released at: https://www.nuget.org/packages/Microsoft.ApplicationInsights.Kubernetes/2.0.5-beta2. Please give it a shoot. Thanks!

**Comment by xiaomi7732** [comment]
And FYI, it looks like the same issue won't be there for 3.0:

* https://github.com/microsoft/ApplicationInsights-Kubernetes/blob/44609e0c740397a237388bd7b908aef771818ca0/src/ApplicationInsights.Kubernetes/Containers/ContainerIdHolder.cs#L66

But it is probably better to have a log entry like it in 2.x. I'll submit another PR for that.

**Comment by xiaomi7732** [comment]
Piggybacked the change in #296 for 3.0

**Comment by xiaomi7732** [comment]
Hey @blushingpenguin, do you mind verifying if 2.0.5-beta2 fixed it for you? I will try to make it a stable release once I hear back from you.

**Comment by xiaomi7732** [comment]
Stable package released:
https://www.nuget.org/packages/Microsoft.ApplicationInsights.Kubernetes/2.0.5
